version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    platform: linux/amd64  # Specifically for M1/M2 Macs if needed
    environment:
      - DB_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"  # This allows connecting to host machine
    